#!/usr/bin/env tsx
/**
 * Generate documentation catalog from markdown files
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { generateCatalog, getLoadedConfig } from '../src/build/scanner.js'

// Get the directory where this script lives
const __dirname = path.dirname(fileURLToPath(import.meta.url))

// Output to note-viewer/src/data/docs-generated.ts (relative to script location)
const OUTPUT_FILE = path.resolve(__dirname, '../src/data/docs-generated.ts')

function main() {
  console.log('📚 Generating documentation catalog...\n')

  // scanner.ts will use the configured content directory
  const catalog = generateCatalog()
  const config = getLoadedConfig()

  // Extract runtime config (site, categories, tags, features, tagRules)
  const runtimeConfig = {
    site: config.site || {},
    categories: config.categories || {},
    tags: config.tags || {},
    tagRules: config.tagRules || [],
    features: config.features || {},
    theme: config.theme || {},
  }

  // Generate TypeScript code
  const output = `// Auto-generated by scripts/generate-docs-catalog.ts
// DO NOT EDIT MANUALLY

import type { DocFile, DocCategory } from '../types/docs.js'
import type { SiteConfig, CategoryConfig, TagConfig, TagRule, FeaturesConfig, ThemeConfig } from '../config.js'

export const docFiles: DocFile[] = ${JSON.stringify(catalog.docFiles, null, 2)}

export const docCategories: DocCategory[] = ${JSON.stringify(catalog.docCategories, null, 2)}

// Runtime configuration (from note-viewer.config.ts)
export const siteConfig: SiteConfig = ${JSON.stringify(runtimeConfig.site, null, 2)}

export const categoryConfig: Record<string, CategoryConfig> = ${JSON.stringify(runtimeConfig.categories, null, 2)}

export const tagConfig: Record<string, TagConfig> = ${JSON.stringify(runtimeConfig.tags, null, 2)}

export const tagRules: TagRule[] = ${JSON.stringify(runtimeConfig.tagRules, null, 2)}

export const featuresConfig: FeaturesConfig = ${JSON.stringify(runtimeConfig.features, null, 2)}

export const themeConfig: ThemeConfig = ${JSON.stringify(runtimeConfig.theme, null, 2)}

// Summary
// --------
// Total files: ${catalog.docFiles.length}
// Total categories: ${catalog.docCategories.length}
`

  // Write output file
  fs.writeFileSync(OUTPUT_FILE, output, 'utf-8')

  console.log('\n📝 Catalog Summary:')
  console.log(`   Total files: ${catalog.docFiles.length}`)
  console.log(`   Total categories: ${catalog.docCategories.length}`)

  console.log('\n📂 Categories:')
  for (const category of catalog.docCategories) {
    console.log(`   - ${category.name}: ${category.files.length} files`)
    for (const file of category.files.slice(0, 3)) {
      console.log(`     • ${file.title}`)
    }
    if (category.files.length > 3) {
      console.log(`     ... and ${category.files.length - 3} more`)
    }
  }

  console.log(`\n✅ Generated ${OUTPUT_FILE}\n`)

  // Show newly discovered files (that weren't in manual catalog)
  const manualCatalogFile = path.resolve(__dirname, '../src/data/docs.ts')
  if (fs.existsSync(manualCatalogFile)) {
    const manualContent = fs.readFileSync(manualCatalogFile, 'utf-8')
    const manualIds = new Set<string>()

    // Extract IDs from manual catalog (simple regex approach)
    const idMatches = manualContent.matchAll(/id:\s*['"]([^'"]+)['"]/g)
    for (const match of idMatches) {
      manualIds.add(match[1])
    }

    const newFiles = catalog.docFiles.filter(f => !manualIds.has(f.id))
    if (newFiles.length > 0) {
      console.log(`🆕 Newly discovered files: ${newFiles.length}`)
      for (const file of newFiles) {
        console.log(`   + ${file.title} (${file.path})`)
      }
      console.log('')
    }
  }
}

main()
