// Auto-generated by scripts/generate-docs-catalog.ts
// DO NOT EDIT MANUALLY

import type { DocFile, DocCategory } from '../types/docs.js'
import type { SiteConfig, CategoryConfig, TagConfig, TagRule, FeaturesConfig, ThemeConfig } from '../config.js'

export const docFiles: DocFile[] = []

export const docCategories: DocCategory[] = []

// Runtime configuration (from note-viewer.config.ts)
export const siteConfig: SiteConfig = {
  "title": "Notes",
  "description": "Markdown documentation viewer",
  "icon": "📓"
}

export const categoryConfig: Record<string, CategoryConfig> = {}

export const tagConfig: Record<string, TagConfig> = {}

export const tagRules: TagRule[] = []

export const featuresConfig: FeaturesConfig = {
  "calculators": false,
  "tagSidebar": true,
  "darkMode": true,
  "search": true
}

export const themeConfig: ThemeConfig = {}

// Summary
// --------
// Total files: 0
// Total categories: 0
