/**
 * Content catalog for the documentation site
 * Maps all markdown files to routes and categories
 *
 * This file now exports from the auto-generated catalog.
 * The catalog is generated by scripts/generate-docs-catalog.ts
 */

import {
  docFiles,
  docCategories,
  siteConfig,
  categoryConfig,
  tagConfig,
  tagRules,
  featuresConfig,
  themeConfig,
} from './docs-generated.js'

// Re-export everything from generated catalog
export { docFiles, docCategories }

// Re-export config
export { siteConfig, categoryConfig, tagConfig, tagRules, featuresConfig, themeConfig }

// Re-export types
export type { DocFile, DocCategory } from '../types/docs.js'

// Get file by ID
export function getDocFile(id: string) {
  return docFiles.find(f => f.id === id)
}

// Get all files in a category
export function getCategoryFiles(categoryId: string) {
  return docFiles.filter(f => f.category === categoryId)
}
