// Auto-generated by scripts/generate-docs-catalog.ts
// DO NOT EDIT MANUALLY

import type { DocFile, DocCategory } from '../types/docs.js'
import type { SiteConfig, CategoryConfig, TagConfig, TagRule, FeaturesConfig, ThemeConfig } from '../config.js'

export const docFiles: DocFile[] = [
  {
    "id": "misc-changelog",
    "title": "Changelog",
    "category": "misc",
    "path": "/CHANGELOG.md",
    "description": "All notable changes to this project will be documented in this file."
  },
  {
    "id": "reference-index",
    "title": "Operations Management",
    "category": "reference",
    "path": "/Index.md",
    "description": "Operations - Design, management, and improvement of business processes"
  },
  {
    "id": "misc-operations_comprehensive_study_guide",
    "title": "Operations Management - Comprehensive Study Guide",
    "category": "misc",
    "path": "/Operations_Comprehensive_Study_Guide.md",
    "description": "Complete study guide covering all 10 weeks of operations management concepts"
  },
  {
    "id": "misc-operations_study_schedule_10week",
    "title": "Operations Management - 10-Week Study Schedule",
    "category": "misc",
    "path": "/Operations_Study_Schedule_10Week.md",
    "description": "Complete 10-week study schedule with weekly rhythm and important dates"
  },
  {
    "id": "misc-operations_t3_2024_notes_sdz",
    "title": "Operations T3 2024 Notes",
    "category": "misc",
    "path": "/Operations_T3_2024_Notes_SDZ.md",
    "description": "Reference notes from Term 3 2024 cohort covering all operations concepts"
  },
  {
    "id": "reference-readme",
    "title": "Operations Management Course Materials",
    "category": "reference",
    "path": "/README.md",
    "description": "Course materials and documentation for the MBA Operations Management course at London Business School."
  },
  {
    "id": "week-1-operations_study_guide_week1",
    "title": "Operations Management - Week 1 Study Guide",
    "category": "week-1",
    "path": "/weeks/week-1-process-view-of-organization/Operations_Study_Guide_Week1.md",
    "description": "Comprehensive study guide for Week 1 covering course overview and process analysis"
  },
  {
    "id": "week-1-week1_1page_study_guide",
    "title": "Week 1 One-Page Study Guide",
    "category": "week-1",
    "path": "/weeks/week-1-process-view-of-organization/Week1_1Page_Study_Guide.md",
    "description": "Condensed one-page summary of Week 1 key concepts and formulas"
  },
  {
    "id": "week-1-week1_cold_call_prep",
    "title": "Week 1 Cold Call Preparation Guide",
    "category": "week-1",
    "path": "/weeks/week-1-process-view-of-organization/Week1_Cold_Call_Prep.md",
    "description": "Preparation guide for likely cold call questions in Week 1 class"
  },
  {
    "id": "week-1-week1_notes",
    "title": "Week 1 - Course Overview and Process View of Organizations",
    "category": "week-1",
    "path": "/weeks/week-1-process-view-of-organization/Week1_Notes.md",
    "description": "Lecture notes covering operations fundamentals, supply-demand matching, and process view concepts"
  },
  {
    "id": "week-1-week1_problemset_11_solution",
    "title": "Week 1 Problem Set 1.1 - One Dozen Cookies Solution",
    "category": "week-1",
    "path": "/weeks/week-1-process-view-of-organization/Week1_ProblemSet_1.1_Solution.md",
    "description": "Step-by-step solution for Problem Set 1.1 analyzing one dozen cookie production"
  },
  {
    "id": "week-1-week1_readings_takeaways",
    "title": "Week 1 Readings - Key Takeaways",
    "category": "week-1",
    "path": "/weeks/week-1-process-view-of-organization/Week1_Readings_Takeaways.md",
    "description": "Summary of key insights from Kristen's Cookie Company case and other Week 1 readings"
  },
  {
    "id": "week-1-week1_slides_study_guide",
    "title": "Week 1 Slides Study Guide",
    "category": "week-1",
    "path": "/weeks/week-1-process-view-of-organization/Week1_Slides_Study_Guide.md",
    "description": "Comprehensive guide based on Week 1 lecture slides covering process view and flow metrics"
  },
  {
    "id": "week-1-week_1_problem_set_solutions",
    "title": "Week 1 Problem Set - Process Flow Foundations Solutions",
    "category": "week-1",
    "path": "/weeks/week-1-process-view-of-organization/Week_1_Problem_Set_Solutions.md",
    "description": "Worked solutions for Week 1 problem set covering Kristen's Cookie Company"
  },
  {
    "id": "week-1-effectiveness_vs_efficiency",
    "title": "Effectiveness vs Efficiency",
    "category": "week-1",
    "path": "/weeks/week-1-process-view-of-organization/effectiveness_vs_efficiency.md",
    "description": "Comparison of effectiveness and efficiency concepts with real-world examples"
  },
  {
    "id": "week-1-mission_vision_values_strategy",
    "title": "Mission, Vision, Values, Strategy",
    "category": "week-1",
    "path": "/weeks/week-1-process-view-of-organization/mission_vision_values_strategy.md",
    "description": "Definitions and distinctions between mission, vision, values, and strategy"
  },
  {
    "id": "week-10-week10_notes",
    "title": "Week 10 - Newsvendor Model",
    "category": "week-10",
    "path": "/weeks/week-10-newsvendor-model/Week10_Notes.md",
    "description": "Lecture notes on managing inventory under uncertainty using the newsvendor model"
  },
  {
    "id": "week-2-donner_company_questions_answers",
    "title": "Donner Company - Discussion Questions & Answers",
    "category": "week-2",
    "path": "/weeks/week-2-process-analysis-evaluating-capacity/Donner_Company_Questions_Answers.md",
    "description": "Discussion questions and answers for Donner Company case preparation"
  },
  {
    "id": "week-2-donner_company_summary",
    "title": "Donner Company Case Summary",
    "category": "week-2",
    "path": "/weeks/week-2-process-analysis-evaluating-capacity/Donner_Company_Summary.md",
    "description": "Summary of Donner Company PCB manufacturing case covering process flow and capacity decisions"
  },
  {
    "id": "week-2-week2_notes",
    "title": "Week 2 - Process Analysis I: Evaluating Process Capacity",
    "category": "week-2",
    "path": "/weeks/week-2-process-analysis-evaluating-capacity/Week2_Notes.md",
    "description": "Lecture notes on process capacity evaluation, Little's Law, and detailed process analysis"
  },
  {
    "id": "week-2-week2_problem_set_solutions",
    "title": "Week 2 Problem Set Solutions - Donner Company and Little's Law",
    "category": "week-2",
    "path": "/weeks/week-2-process-analysis-evaluating-capacity/Week2_Problem_Set_Solutions.md",
    "description": "Worked solutions for Week 2 problem set covering Donner Company analysis and Little's Law"
  },
  {
    "id": "week-3-week3_notes",
    "title": "Week 3 - Process Analysis II: Analyzing Assembly Operations",
    "category": "week-3",
    "path": "/weeks/week-3-assembly-operations-line-balancing/Week3_Notes.md",
    "description": "Lecture notes on assembly operations, line balancing, and process type classification"
  },
  {
    "id": "week-4-week4_notes",
    "title": "Week 4 - Process Analysis Wrap-up",
    "category": "week-4",
    "path": "/weeks/week-4-process-analysis-wrapup/Week4_Notes.md",
    "description": "Lecture notes on mass customization, delayed differentiation, and advanced line balancing"
  },
  {
    "id": "week-5-week5_notes",
    "title": "Week 5 - Project Management",
    "category": "week-5",
    "path": "/weeks/week-5-project-management/Week5_Notes.md",
    "description": "Lecture notes on project management, critical path method, PERT, and project crashing"
  },
  {
    "id": "week-6-week6_notes",
    "title": "Week 6 - Setup Times and Inventory Management",
    "category": "week-6",
    "path": "/weeks/week-6-setup-times-inventory-management/Week6_Notes.md",
    "description": "Lecture notes on setup times, batch sizing, EOQ model, and inventory management"
  },
  {
    "id": "week-7-week7_notes",
    "title": "Week 7 - Waiting Time Problems",
    "category": "week-7",
    "path": "/weeks/week-7-waiting-time-problems/Week7_Notes.md",
    "description": "Lecture notes on variability's impact on waiting times and queue management"
  },
  {
    "id": "week-8-week8_notes",
    "title": "Week 8 - Throughput Losses",
    "category": "week-8",
    "path": "/weeks/week-8-throughput-losses/Week8_Notes.md",
    "description": "Lecture notes on throughput losses when customers won't wait"
  },
  {
    "id": "week-9-week9_notes",
    "title": "Week 9 - Introduction to Quality",
    "category": "week-9",
    "path": "/weeks/week-9-quality-management/Week9_Notes.md",
    "description": "Lecture notes on quality dimensions, cost of quality, and statistical process control"
  }
]

export const docCategories: DocCategory[] = [
  {
    "id": "week-1",
    "name": "Week 1",
    "description": "Materials for Week 1",
    "files": [
      {
        "id": "week-1-effectiveness_vs_efficiency",
        "title": "Effectiveness vs Efficiency",
        "category": "week-1",
        "path": "/weeks/week-1-process-view-of-organization/effectiveness_vs_efficiency.md",
        "description": "Comparison of effectiveness and efficiency concepts with real-world examples"
      },
      {
        "id": "week-1-mission_vision_values_strategy",
        "title": "Mission, Vision, Values, Strategy",
        "category": "week-1",
        "path": "/weeks/week-1-process-view-of-organization/mission_vision_values_strategy.md",
        "description": "Definitions and distinctions between mission, vision, values, and strategy"
      },
      {
        "id": "week-1-operations_study_guide_week1",
        "title": "Operations Management - Week 1 Study Guide",
        "category": "week-1",
        "path": "/weeks/week-1-process-view-of-organization/Operations_Study_Guide_Week1.md",
        "description": "Comprehensive study guide for Week 1 covering course overview and process analysis"
      },
      {
        "id": "week-1-week1_notes",
        "title": "Week 1 - Course Overview and Process View of Organizations",
        "category": "week-1",
        "path": "/weeks/week-1-process-view-of-organization/Week1_Notes.md",
        "description": "Lecture notes covering operations fundamentals, supply-demand matching, and process view concepts"
      },
      {
        "id": "week-1-week1_cold_call_prep",
        "title": "Week 1 Cold Call Preparation Guide",
        "category": "week-1",
        "path": "/weeks/week-1-process-view-of-organization/Week1_Cold_Call_Prep.md",
        "description": "Preparation guide for likely cold call questions in Week 1 class"
      },
      {
        "id": "week-1-week1_1page_study_guide",
        "title": "Week 1 One-Page Study Guide",
        "category": "week-1",
        "path": "/weeks/week-1-process-view-of-organization/Week1_1Page_Study_Guide.md",
        "description": "Condensed one-page summary of Week 1 key concepts and formulas"
      },
      {
        "id": "week-1-week_1_problem_set_solutions",
        "title": "Week 1 Problem Set - Process Flow Foundations Solutions",
        "category": "week-1",
        "path": "/weeks/week-1-process-view-of-organization/Week_1_Problem_Set_Solutions.md",
        "description": "Worked solutions for Week 1 problem set covering Kristen's Cookie Company"
      },
      {
        "id": "week-1-week1_problemset_11_solution",
        "title": "Week 1 Problem Set 1.1 - One Dozen Cookies Solution",
        "category": "week-1",
        "path": "/weeks/week-1-process-view-of-organization/Week1_ProblemSet_1.1_Solution.md",
        "description": "Step-by-step solution for Problem Set 1.1 analyzing one dozen cookie production"
      },
      {
        "id": "week-1-week1_readings_takeaways",
        "title": "Week 1 Readings - Key Takeaways",
        "category": "week-1",
        "path": "/weeks/week-1-process-view-of-organization/Week1_Readings_Takeaways.md",
        "description": "Summary of key insights from Kristen's Cookie Company case and other Week 1 readings"
      },
      {
        "id": "week-1-week1_slides_study_guide",
        "title": "Week 1 Slides Study Guide",
        "category": "week-1",
        "path": "/weeks/week-1-process-view-of-organization/Week1_Slides_Study_Guide.md",
        "description": "Comprehensive guide based on Week 1 lecture slides covering process view and flow metrics"
      }
    ]
  },
  {
    "id": "week-2",
    "name": "Week 2",
    "description": "Materials for Week 2",
    "files": [
      {
        "id": "week-2-donner_company_questions_answers",
        "title": "Donner Company - Discussion Questions & Answers",
        "category": "week-2",
        "path": "/weeks/week-2-process-analysis-evaluating-capacity/Donner_Company_Questions_Answers.md",
        "description": "Discussion questions and answers for Donner Company case preparation"
      },
      {
        "id": "week-2-donner_company_summary",
        "title": "Donner Company Case Summary",
        "category": "week-2",
        "path": "/weeks/week-2-process-analysis-evaluating-capacity/Donner_Company_Summary.md",
        "description": "Summary of Donner Company PCB manufacturing case covering process flow and capacity decisions"
      },
      {
        "id": "week-2-week2_notes",
        "title": "Week 2 - Process Analysis I: Evaluating Process Capacity",
        "category": "week-2",
        "path": "/weeks/week-2-process-analysis-evaluating-capacity/Week2_Notes.md",
        "description": "Lecture notes on process capacity evaluation, Little's Law, and detailed process analysis"
      },
      {
        "id": "week-2-week2_problem_set_solutions",
        "title": "Week 2 Problem Set Solutions - Donner Company and Little's Law",
        "category": "week-2",
        "path": "/weeks/week-2-process-analysis-evaluating-capacity/Week2_Problem_Set_Solutions.md",
        "description": "Worked solutions for Week 2 problem set covering Donner Company analysis and Little's Law"
      }
    ]
  },
  {
    "id": "week-3",
    "name": "Week 3",
    "description": "Materials for Week 3",
    "files": [
      {
        "id": "week-3-week3_notes",
        "title": "Week 3 - Process Analysis II: Analyzing Assembly Operations",
        "category": "week-3",
        "path": "/weeks/week-3-assembly-operations-line-balancing/Week3_Notes.md",
        "description": "Lecture notes on assembly operations, line balancing, and process type classification"
      }
    ]
  },
  {
    "id": "week-4",
    "name": "Week 4",
    "description": "Materials for Week 4",
    "files": [
      {
        "id": "week-4-week4_notes",
        "title": "Week 4 - Process Analysis Wrap-up",
        "category": "week-4",
        "path": "/weeks/week-4-process-analysis-wrapup/Week4_Notes.md",
        "description": "Lecture notes on mass customization, delayed differentiation, and advanced line balancing"
      }
    ]
  },
  {
    "id": "week-5",
    "name": "Week 5",
    "description": "Materials for Week 5",
    "files": [
      {
        "id": "week-5-week5_notes",
        "title": "Week 5 - Project Management",
        "category": "week-5",
        "path": "/weeks/week-5-project-management/Week5_Notes.md",
        "description": "Lecture notes on project management, critical path method, PERT, and project crashing"
      }
    ]
  },
  {
    "id": "week-6",
    "name": "Week 6",
    "description": "Materials for Week 6",
    "files": [
      {
        "id": "week-6-week6_notes",
        "title": "Week 6 - Setup Times and Inventory Management",
        "category": "week-6",
        "path": "/weeks/week-6-setup-times-inventory-management/Week6_Notes.md",
        "description": "Lecture notes on setup times, batch sizing, EOQ model, and inventory management"
      }
    ]
  },
  {
    "id": "week-7",
    "name": "Week 7",
    "description": "Materials for Week 7",
    "files": [
      {
        "id": "week-7-week7_notes",
        "title": "Week 7 - Waiting Time Problems",
        "category": "week-7",
        "path": "/weeks/week-7-waiting-time-problems/Week7_Notes.md",
        "description": "Lecture notes on variability's impact on waiting times and queue management"
      }
    ]
  },
  {
    "id": "week-8",
    "name": "Week 8",
    "description": "Materials for Week 8",
    "files": [
      {
        "id": "week-8-week8_notes",
        "title": "Week 8 - Throughput Losses",
        "category": "week-8",
        "path": "/weeks/week-8-throughput-losses/Week8_Notes.md",
        "description": "Lecture notes on throughput losses when customers won't wait"
      }
    ]
  },
  {
    "id": "week-9",
    "name": "Week 9",
    "description": "Materials for Week 9",
    "files": [
      {
        "id": "week-9-week9_notes",
        "title": "Week 9 - Introduction to Quality",
        "category": "week-9",
        "path": "/weeks/week-9-quality-management/Week9_Notes.md",
        "description": "Lecture notes on quality dimensions, cost of quality, and statistical process control"
      }
    ]
  },
  {
    "id": "week-10",
    "name": "Week 10",
    "description": "Materials for Week 10",
    "files": [
      {
        "id": "week-10-week10_notes",
        "title": "Week 10 - Newsvendor Model",
        "category": "week-10",
        "path": "/weeks/week-10-newsvendor-model/Week10_Notes.md",
        "description": "Lecture notes on managing inventory under uncertainty using the newsvendor model"
      }
    ]
  },
  {
    "id": "misc",
    "name": "Miscellaneous",
    "description": "Additional notes and resources",
    "files": [
      {
        "id": "misc-changelog",
        "title": "Changelog",
        "category": "misc",
        "path": "/CHANGELOG.md",
        "description": "All notable changes to this project will be documented in this file."
      },
      {
        "id": "misc-operations_study_schedule_10week",
        "title": "Operations Management - 10-Week Study Schedule",
        "category": "misc",
        "path": "/Operations_Study_Schedule_10Week.md",
        "description": "Complete 10-week study schedule with weekly rhythm and important dates"
      },
      {
        "id": "misc-operations_comprehensive_study_guide",
        "title": "Operations Management - Comprehensive Study Guide",
        "category": "misc",
        "path": "/Operations_Comprehensive_Study_Guide.md",
        "description": "Complete study guide covering all 10 weeks of operations management concepts"
      },
      {
        "id": "misc-operations_t3_2024_notes_sdz",
        "title": "Operations T3 2024 Notes",
        "category": "misc",
        "path": "/Operations_T3_2024_Notes_SDZ.md",
        "description": "Reference notes from Term 3 2024 cohort covering all operations concepts"
      }
    ]
  },
  {
    "id": "reference",
    "name": "Reference",
    "description": "Index and reference documentation",
    "files": [
      {
        "id": "reference-index",
        "title": "Operations Management",
        "category": "reference",
        "path": "/Index.md",
        "description": "Operations - Design, management, and improvement of business processes"
      },
      {
        "id": "reference-readme",
        "title": "Operations Management Course Materials",
        "category": "reference",
        "path": "/README.md",
        "description": "Course materials and documentation for the MBA Operations Management course at London Business School."
      }
    ]
  }
]

// Runtime configuration (from note-viewer.config.ts)
export const siteConfig: SiteConfig = {
  "title": "Operations Management",
  "description": "MBA Operations Course - LBS Term 1 2026",
  "icon": "📊"
}

export const categoryConfig: Record<string, CategoryConfig> = {}

export const tagConfig: Record<string, TagConfig> = {}

export const tagRules: TagRule[] = []

export const featuresConfig: FeaturesConfig = {
  "calculators": false,
  "tagSidebar": true,
  "darkMode": true,
  "search": true
}

export const themeConfig: ThemeConfig = {
  "light": {},
  "dark": {}
}

// Summary
// --------
// Total files: 28
// Total categories: 12
