// Auto-generated by scripts/generate-docs-catalog.ts
// DO NOT EDIT MANUALLY

import type { DocFile, DocCategory } from '../types/docs.js'
import type { SiteConfig, CategoryConfig, TagConfig, TagRule, FeaturesConfig, ThemeConfig } from '../config.js'

export const docFiles: DocFile[] = [
  {
    "id": "misc-changelog",
    "title": "Changelog",
    "category": "misc",
    "path": "/CHANGELOG.md",
    "description": "All notable changes to this project will be documented in this file."
  },
  {
    "id": "reference-index",
    "title": "Operations Management",
    "category": "reference",
    "path": "/Index.md",
    "description": "Operations - Design, management, and improvement of business processes"
  },
  {
    "id": "misc-operations_comprehensive_study_guide",
    "title": "Operations Management - Comprehensive Study Guide",
    "category": "misc",
    "path": "/Operations_Comprehensive_Study_Guide.md",
    "description": "> **Course:** BUSA90227 - Operations Management"
  },
  {
    "id": "misc-operations_study_schedule_10week",
    "title": "Operations Management - 10-Week Study Schedule",
    "category": "misc",
    "path": "/Operations_Study_Schedule_10Week.md",
    "description": "> **Student:** Shawn D'souza (ID: 1552574)"
  },
  {
    "id": "misc-operations_t3_2024_notes_sdz",
    "title": "Week 1 -- Course Overview and Introduction to the Process view of the organization",
    "category": "misc",
    "path": "/Operations_T3_2024_Notes_SDZ.md",
    "description": "- Effective operations management is about effectively matching supply"
  },
  {
    "id": "reference-readme",
    "title": "Operations Management Course Materials",
    "category": "reference",
    "path": "/README.md",
    "description": "Course materials and documentation for the MBA Operations Management course at London Business School."
  },
  {
    "id": "week-1-operations_study_guide_week1",
    "title": "Operations Management - Week 1 Study Guide",
    "category": "week-1",
    "path": "/weeks/week-1-process-view-of-organization/Operations_Study_Guide_Week1.md",
    "description": "> **Course:** Operations Management, London Business School, Term 1 2026"
  },
  {
    "id": "week-1-week1_1page_study_guide",
    "title": "Operations Management - Week 1: One-Page Study Guide",
    "category": "week-1",
    "path": "/weeks/week-1-process-view-of-organization/Week1_1Page_Study_Guide.md",
    "description": "> **Student:** Shawn D'souza | **ID:** 1552574 | **Class:** Wed 6pm-9:15pm"
  },
  {
    "id": "week-1-week1_cold_call_prep",
    "title": "Week 1 Cold Call Preparation Guide",
    "category": "week-1",
    "path": "/weeks/week-1-process-view-of-organization/Week1_Cold_Call_Prep.md",
    "description": "> **Goal:** Be ready to answer questions confidently in class. Cold calling counts toward your 30% participation grade."
  },
  {
    "id": "week-1-week1_notes",
    "title": "Week 1 - Course Overview and Process View of Organizations",
    "category": "week-1",
    "path": "/weeks/week-1-process-view-of-organization/Week1_Notes.md",
    "description": "> **Topic:** Course Overview and Introduction to the Process View of the Organization"
  },
  {
    "id": "week-1-week1_problemset_11_solution",
    "title": "Week 1 Problem Set 1.1 - One Dozen Cookies (Solution)",
    "category": "week-1",
    "path": "/weeks/week-1-process-view-of-organization/Week1_ProblemSet_1.1_Solution.md",
    "description": "> **Case:** Kristen's Cookie Company"
  },
  {
    "id": "week-1-week1_readings_takeaways",
    "title": "Week 1 Readings - Key Takeaways",
    "category": "week-1",
    "path": "/weeks/week-1-process-view-of-organization/Week1_Readings_Takeaways.md",
    "description": "How to analyze and optimize a simple production process to maximize efficiency and profit."
  },
  {
    "id": "week-1-week1_slides_study_guide",
    "title": "Week 1 Slides Study Guide",
    "category": "week-1",
    "path": "/weeks/week-1-process-view-of-organization/Week1_Slides_Study_Guide.md",
    "description": "> **Course:** BUSA90227 - Operations Management"
  },
  {
    "id": "week-1-effectiveness_vs_efficiency",
    "title": "Effectiveness vs Efficiency",
    "category": "week-1",
    "path": "/weeks/week-1-process-view-of-organization/effectiveness_vs_efficiency.md",
    "description": "**Effectiveness** - \"Doing the right things\""
  },
  {
    "id": "week-1-mission_vision_values_strategy",
    "title": "Mission, Vision, Values, Strategy",
    "category": "week-1",
    "path": "/weeks/week-1-process-view-of-organization/mission_vision_values_strategy.md",
    "description": "**What we do today, who we do it for, and why**"
  },
  {
    "id": "week-10-week10_notes",
    "title": "Week 10 - Newsvendor Model",
    "category": "week-10",
    "path": "/weeks/week-10-newsvendor-model/Week10_Notes.md",
    "description": "> **Topic:** Managing Inventory Under Uncertainty - The Newsvendor Model"
  },
  {
    "id": "week-2-donner_company_summary",
    "title": "Donner Company Case Summary",
    "category": "week-2",
    "path": "/weeks/week-2-process-analysis-evaluating-capacity/Donner_Company_Summary.md",
    "description": "- **Business:** Contract manufacturer of printed circuit boards (PCBs) for electronics manufacturers"
  },
  {
    "id": "week-2-week2_notes",
    "title": "Week 2 - Process Analysis I: Evaluating Process Capacity",
    "category": "week-2",
    "path": "/weeks/week-2-process-analysis-evaluating-capacity/Week2_Notes.md",
    "description": "> **Topic:** Process Analysis I: Evaluating Process Capacity and Performing Detailed Process Analysis"
  },
  {
    "id": "week-3-week3_notes",
    "title": "Week 3 - Process Analysis II: Analyzing Assembly Operations",
    "category": "week-3",
    "path": "/weeks/week-3-assembly-operations-line-balancing/Week3_Notes.md",
    "description": "> **Topic:** Process Analysis II: Analyzing Assembly Operations and Line Balancing"
  },
  {
    "id": "week-4-week4_notes",
    "title": "Week 4 - Process Analysis Wrap-up",
    "category": "week-4",
    "path": "/weeks/week-4-process-analysis-wrapup/Week4_Notes.md",
    "description": "> **Topic:** Process Analysis Wrap-up - Mass Customization, Line Balancing, and Scaling Production"
  },
  {
    "id": "week-5-week5_notes",
    "title": "Week 5 - Project Management",
    "category": "week-5",
    "path": "/weeks/week-5-project-management/Week5_Notes.md",
    "description": "> **Topic:** Project Management - Critical Path Method, PERT, and Project Crashing"
  },
  {
    "id": "week-6-week6_notes",
    "title": "Week 6 - Setup Times and Inventory Management",
    "category": "week-6",
    "path": "/weeks/week-6-setup-times-inventory-management/Week6_Notes.md",
    "description": "> **Topic:** Setup Times, Batch Size, EOQ Model, and Inventory Management"
  },
  {
    "id": "week-7-week7_notes",
    "title": "Week 7 - Waiting Time Problems",
    "category": "week-7",
    "path": "/weeks/week-7-waiting-time-problems/Week7_Notes.md",
    "description": "> **Topic:** Variability and Its Impact on Process Performance - Waiting Time Problems"
  },
  {
    "id": "week-8-week8_notes",
    "title": "Week 8 - Throughput Losses",
    "category": "week-8",
    "path": "/weeks/week-8-throughput-losses/Week8_Notes.md",
    "description": "> **Topic:** Variability and Its Impact on Process Performance - Throughput Losses"
  },
  {
    "id": "week-9-week9_notes",
    "title": "Week 9 - Introduction to Quality",
    "category": "week-9",
    "path": "/weeks/week-9-quality-management/Week9_Notes.md",
    "description": "> **Topic:** Quality Management - Dimensions, Costs, and Statistical Process Control"
  }
]

export const docCategories: DocCategory[] = [
  {
    "id": "week-1",
    "name": "Week 1",
    "description": "Materials for Week 1",
    "files": [
      {
        "id": "week-1-effectiveness_vs_efficiency",
        "title": "Effectiveness vs Efficiency",
        "category": "week-1",
        "path": "/weeks/week-1-process-view-of-organization/effectiveness_vs_efficiency.md",
        "description": "**Effectiveness** - \"Doing the right things\""
      },
      {
        "id": "week-1-mission_vision_values_strategy",
        "title": "Mission, Vision, Values, Strategy",
        "category": "week-1",
        "path": "/weeks/week-1-process-view-of-organization/mission_vision_values_strategy.md",
        "description": "**What we do today, who we do it for, and why**"
      },
      {
        "id": "week-1-operations_study_guide_week1",
        "title": "Operations Management - Week 1 Study Guide",
        "category": "week-1",
        "path": "/weeks/week-1-process-view-of-organization/Operations_Study_Guide_Week1.md",
        "description": "> **Course:** Operations Management, London Business School, Term 1 2026"
      },
      {
        "id": "week-1-week1_1page_study_guide",
        "title": "Operations Management - Week 1: One-Page Study Guide",
        "category": "week-1",
        "path": "/weeks/week-1-process-view-of-organization/Week1_1Page_Study_Guide.md",
        "description": "> **Student:** Shawn D'souza | **ID:** 1552574 | **Class:** Wed 6pm-9:15pm"
      },
      {
        "id": "week-1-week1_notes",
        "title": "Week 1 - Course Overview and Process View of Organizations",
        "category": "week-1",
        "path": "/weeks/week-1-process-view-of-organization/Week1_Notes.md",
        "description": "> **Topic:** Course Overview and Introduction to the Process View of the Organization"
      },
      {
        "id": "week-1-week1_cold_call_prep",
        "title": "Week 1 Cold Call Preparation Guide",
        "category": "week-1",
        "path": "/weeks/week-1-process-view-of-organization/Week1_Cold_Call_Prep.md",
        "description": "> **Goal:** Be ready to answer questions confidently in class. Cold calling counts toward your 30% participation grade."
      },
      {
        "id": "week-1-week1_problemset_11_solution",
        "title": "Week 1 Problem Set 1.1 - One Dozen Cookies (Solution)",
        "category": "week-1",
        "path": "/weeks/week-1-process-view-of-organization/Week1_ProblemSet_1.1_Solution.md",
        "description": "> **Case:** Kristen's Cookie Company"
      },
      {
        "id": "week-1-week1_readings_takeaways",
        "title": "Week 1 Readings - Key Takeaways",
        "category": "week-1",
        "path": "/weeks/week-1-process-view-of-organization/Week1_Readings_Takeaways.md",
        "description": "How to analyze and optimize a simple production process to maximize efficiency and profit."
      },
      {
        "id": "week-1-week1_slides_study_guide",
        "title": "Week 1 Slides Study Guide",
        "category": "week-1",
        "path": "/weeks/week-1-process-view-of-organization/Week1_Slides_Study_Guide.md",
        "description": "> **Course:** BUSA90227 - Operations Management"
      }
    ]
  },
  {
    "id": "week-2",
    "name": "Week 2",
    "description": "Materials for Week 2",
    "files": [
      {
        "id": "week-2-donner_company_summary",
        "title": "Donner Company Case Summary",
        "category": "week-2",
        "path": "/weeks/week-2-process-analysis-evaluating-capacity/Donner_Company_Summary.md",
        "description": "- **Business:** Contract manufacturer of printed circuit boards (PCBs) for electronics manufacturers"
      },
      {
        "id": "week-2-week2_notes",
        "title": "Week 2 - Process Analysis I: Evaluating Process Capacity",
        "category": "week-2",
        "path": "/weeks/week-2-process-analysis-evaluating-capacity/Week2_Notes.md",
        "description": "> **Topic:** Process Analysis I: Evaluating Process Capacity and Performing Detailed Process Analysis"
      }
    ]
  },
  {
    "id": "week-3",
    "name": "Week 3",
    "description": "Materials for Week 3",
    "files": [
      {
        "id": "week-3-week3_notes",
        "title": "Week 3 - Process Analysis II: Analyzing Assembly Operations",
        "category": "week-3",
        "path": "/weeks/week-3-assembly-operations-line-balancing/Week3_Notes.md",
        "description": "> **Topic:** Process Analysis II: Analyzing Assembly Operations and Line Balancing"
      }
    ]
  },
  {
    "id": "week-4",
    "name": "Week 4",
    "description": "Materials for Week 4",
    "files": [
      {
        "id": "week-4-week4_notes",
        "title": "Week 4 - Process Analysis Wrap-up",
        "category": "week-4",
        "path": "/weeks/week-4-process-analysis-wrapup/Week4_Notes.md",
        "description": "> **Topic:** Process Analysis Wrap-up - Mass Customization, Line Balancing, and Scaling Production"
      }
    ]
  },
  {
    "id": "week-5",
    "name": "Week 5",
    "description": "Materials for Week 5",
    "files": [
      {
        "id": "week-5-week5_notes",
        "title": "Week 5 - Project Management",
        "category": "week-5",
        "path": "/weeks/week-5-project-management/Week5_Notes.md",
        "description": "> **Topic:** Project Management - Critical Path Method, PERT, and Project Crashing"
      }
    ]
  },
  {
    "id": "week-6",
    "name": "Week 6",
    "description": "Materials for Week 6",
    "files": [
      {
        "id": "week-6-week6_notes",
        "title": "Week 6 - Setup Times and Inventory Management",
        "category": "week-6",
        "path": "/weeks/week-6-setup-times-inventory-management/Week6_Notes.md",
        "description": "> **Topic:** Setup Times, Batch Size, EOQ Model, and Inventory Management"
      }
    ]
  },
  {
    "id": "week-7",
    "name": "Week 7",
    "description": "Materials for Week 7",
    "files": [
      {
        "id": "week-7-week7_notes",
        "title": "Week 7 - Waiting Time Problems",
        "category": "week-7",
        "path": "/weeks/week-7-waiting-time-problems/Week7_Notes.md",
        "description": "> **Topic:** Variability and Its Impact on Process Performance - Waiting Time Problems"
      }
    ]
  },
  {
    "id": "week-8",
    "name": "Week 8",
    "description": "Materials for Week 8",
    "files": [
      {
        "id": "week-8-week8_notes",
        "title": "Week 8 - Throughput Losses",
        "category": "week-8",
        "path": "/weeks/week-8-throughput-losses/Week8_Notes.md",
        "description": "> **Topic:** Variability and Its Impact on Process Performance - Throughput Losses"
      }
    ]
  },
  {
    "id": "week-9",
    "name": "Week 9",
    "description": "Materials for Week 9",
    "files": [
      {
        "id": "week-9-week9_notes",
        "title": "Week 9 - Introduction to Quality",
        "category": "week-9",
        "path": "/weeks/week-9-quality-management/Week9_Notes.md",
        "description": "> **Topic:** Quality Management - Dimensions, Costs, and Statistical Process Control"
      }
    ]
  },
  {
    "id": "week-10",
    "name": "Week 10",
    "description": "Materials for Week 10",
    "files": [
      {
        "id": "week-10-week10_notes",
        "title": "Week 10 - Newsvendor Model",
        "category": "week-10",
        "path": "/weeks/week-10-newsvendor-model/Week10_Notes.md",
        "description": "> **Topic:** Managing Inventory Under Uncertainty - The Newsvendor Model"
      }
    ]
  },
  {
    "id": "misc",
    "name": "Miscellaneous",
    "description": "Additional notes and resources",
    "files": [
      {
        "id": "misc-changelog",
        "title": "Changelog",
        "category": "misc",
        "path": "/CHANGELOG.md",
        "description": "All notable changes to this project will be documented in this file."
      },
      {
        "id": "misc-operations_study_schedule_10week",
        "title": "Operations Management - 10-Week Study Schedule",
        "category": "misc",
        "path": "/Operations_Study_Schedule_10Week.md",
        "description": "> **Student:** Shawn D'souza (ID: 1552574)"
      },
      {
        "id": "misc-operations_comprehensive_study_guide",
        "title": "Operations Management - Comprehensive Study Guide",
        "category": "misc",
        "path": "/Operations_Comprehensive_Study_Guide.md",
        "description": "> **Course:** BUSA90227 - Operations Management"
      },
      {
        "id": "misc-operations_t3_2024_notes_sdz",
        "title": "Week 1 -- Course Overview and Introduction to the Process view of the organization",
        "category": "misc",
        "path": "/Operations_T3_2024_Notes_SDZ.md",
        "description": "- Effective operations management is about effectively matching supply"
      }
    ]
  },
  {
    "id": "reference",
    "name": "Reference",
    "description": "Index and reference documentation",
    "files": [
      {
        "id": "reference-index",
        "title": "Operations Management",
        "category": "reference",
        "path": "/Index.md",
        "description": "Operations - Design, management, and improvement of business processes"
      },
      {
        "id": "reference-readme",
        "title": "Operations Management Course Materials",
        "category": "reference",
        "path": "/README.md",
        "description": "Course materials and documentation for the MBA Operations Management course at London Business School."
      }
    ]
  }
]

// Runtime configuration (from note-viewer.config.ts)
export const siteConfig: SiteConfig = {
  "title": "Operations Management",
  "description": "MBA Operations Course - LBS Term 1 2026",
  "icon": "📊"
}

export const categoryConfig: Record<string, CategoryConfig> = {}

export const tagConfig: Record<string, TagConfig> = {}

export const tagRules: TagRule[] = []

export const featuresConfig: FeaturesConfig = {
  "calculators": false,
  "tagSidebar": true,
  "darkMode": true,
  "search": true
}

export const themeConfig: ThemeConfig = {
  "light": {},
  "dark": {}
}

// Summary
// --------
// Total files: 25
// Total categories: 12
